twig:
    default_path: '%kernel.project_dir%/templates'
    debug: '%kernel.debug%'
    strict_variables: '%kernel.debug%'
    globals:
        app_name: '%env(APP_NAME)%'
        app_version: '%env(APP_VERSION)%'
        app_author: '%env(APP_AUTHOR)%'
        app_git_url: '%env(APP_GIT_URL)%'